audio:
- changed-files:
  - any-glob-to-any-file: 'src/Paintvale.Audio*/**'

cpu:
- changed-files:
  - any-glob-to-any-file: ['src/ARMeilleure/**', 'src/Paintvale.Cpu/**', 'src/Paintvale.Memory/**']

gpu:
- changed-files:
  - any-glob-to-any-file: ['src/Paintvale.Graphics.*/**', 'src/Spv.Generator/**', 'src/Paintvale.ShaderTools/**']

'graphics-backend:opengl':
- changed-files:
  - any-glob-to-any-file: 'src/Paintvale.Graphics.OpenGL/**'

'graphics-backend:vulkan':
- changed-files:
  - any-glob-to-any-file: ['src/Paintvale.Graphics.Vulkan/**', 'src/Spv.Generator/**']

'graphics-backend:metal':
  - changed-files:
      - any-glob-to-any-file: ['src/Paintvale.Graphics.Metal/**', 'src/Paintvale.Graphics.Metal.SharpMetalExtensions/**']

gui:
- changed-files:
  - any-glob-to-any-file: ['src/Paintvale/**', 'src/Paintvale.UI.Common/**', 'src/Paintvale.UI.LocaleGenerator/**']

horizon:
- changed-files:
  - any-glob-to-any-file: ['src/Paintvale.HLE/**', 'src/Paintvale.Horizon/**']

kernel:
- changed-files:
  - any-glob-to-any-file: 'src/Paintvale.HLE/HOS/Kernel/**'

infra:
- changed-files:
  - any-glob-to-any-file: ['.github/**', 'distribution/**', 'Directory.Packages.props', 'src/Paintvale.BuildValidationTasks/**']

documentation:
- changed-files:
  - any-glob-to-any-file: 'docs/**'

ldn:
- changed-files:
  - any-glob-to-any-file: 'src/Paintvale.HLE/HOS/Services/Ldn/**'
